<?php

/**
 * @file
 * Install, update and uninstall functions for the social installation profile.
 */

use Drupal\user\Entity\User;
use Drupal\user\Entity\Role;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function open_web_app_install() {
  include_once DRUPAL_ROOT . '/core/profiles/standard/standard.install';
  standard_install();

}
